services:
  ai-agent-hub:
    build: .
    env_file: .env
    environment:
      PORT: 8500
    ports:
      - "8500:8500"
    volumes:
      - .:/app
    command: >
      /bin/sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      streamlit run app.py --server.port=8500 --server.address=0.0.0.0
      "
